(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var e=this||self;var g=class{constructor(a,b){this.g=b===f?a:""}};g.prototype.i=!0;g.prototype.h=function(){return this.g.toString()};g.prototype.toString=function(){return this.g.toString()};function h(a){return a instanceof g&&a.constructor===g?a.g:"type_error:SafeUrl"}var l=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,f={};function m(a){m[" "](a);return a}m[" "]=function(){};function q(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)q(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function r(){var a=t;try{var b;if(b=!!a&&null!=a.location.href)a:{try{m(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}};var u=(a,b,c,d,n)=>{if(n)c=a+("&"+b+"="+c);else{var k="&"+b+"=";let p=a.indexOf(k);0>p?c=a+k+c:(p+=k.length,k=a.indexOf("&",p),c=0<=k?a.substring(0,p)+c+a.substring(k):a.substring(0,p)+c)}return 2E3<c.length?void 0!==d?u(a,b,d,void 0,n):a:c};var v=document,w=window;var x={};var y=class{};class z extends y{constructor(a){super();if(x!==x)throw Error("Bad secret");this.g=a}toString(){return this.g}}var A=new z("about:invalid#zTSz");function B(a){if(a instanceof y)if(a instanceof z)a=a.g;else throw Error("wrong type");else a=h(a);return a};class C{constructor(a){this.j=a}}function D(a){return new C(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const E=new C(a=>/^[^:]*([/?#]|$)/.test(a));var F=D("http"),G=D("https"),H=D("ftp"),I=D("mailto");const J=[D("data"),F,G,I,H,E];function K(a,b=J){for(let c=0;c<b.length;++c){const d=b[c];if(d instanceof C&&d.j(a))return new z(a)}}function L(a,b=J){return K(a,b)||A};const M=[F,G,I,H,E,D("market"),D("itms"),D("intent"),D("itms-appss")]; 
var N=()=>{var a=`${"http:"===w.location.protocol?"http:":"https:"}//${"pagead2.googlesyndication.com"}/pagead/gen_204`;return b=>{b={id:"unsafeurl",ctx:600,url:b};var c=[];for(d in b)q(d,b[d],c);var d=c.join("&");if(d){b=a.indexOf("#");0>b&&(b=a.length);c=a.indexOf("?");if(0>c||c>b){c=b;var n=""}else n=a.substring(c+1,b);b=[a.substr(0,c),n,a.substr(b)];c=b[1];b[1]=d?c?c+"&"+d:d:c;d=b[0]+(b[1]?"?"+b[1]:"")+b[2]}else d=a;navigator.sendBeacon&&navigator.sendBeacon(d,"")}};var O=!!window.google_async_iframe_id;let t=O&&window.parent||window;let P=null;var Q=()=>{const a=e.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},R=()=>{const a=e.performance;return a&&a.now?a.now():null};class S{constructor(a,b){var c=R()||Q();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const T=e.performance,U=!!(T&&T.mark&&T.measure&&T.clearMarks),V=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=U){var b;if(null===P){P="";try{a="";try{a=e.top.location.hash}catch(c){a=e.location.hash}a&&(P=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=P;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function aa(a){a&&T&&V()&&(T.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),T.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class ba{constructor(){var a=W;this.g=[];this.i=a||e;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.g=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.h=V()||(null!=b?b:1>Math.random())}start(a,b){if(!this.h)return null;a=new S(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;T&&V()&&T.mark(b);return a}end(a){if(this.h&&"number"===typeof a.value){a.duration=(R()||Q())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;T&&V()&&T.mark(b);!this.h||2048<this.g.length|| 
this.g.push(a)}}};if(O&&!r()){let a="."+v.domain;try{for(;2<a.split(".").length&&!r();)v.domain=a=a.substr(a.indexOf(".")+1),t=window.parent}catch(b){}r()||(t=window)}const W=t,X=new ba;var Y=()=>{W.google_measure_js_timing||(X.h=!1,X.g!=X.i.google_js_reporting_queue&&(V()&&Array.prototype.forEach.call(X.g,aa,void 0),X.g.length=0))};"number"!==typeof W.google_srt&&(W.google_srt=Math.random()); 
if("complete"==W.document.readyState)Y();else if(X.h){var ca=()=>{Y()},Z=W;Z.addEventListener&&Z.addEventListener.call(Z,"load",ca,!1)};window.bgz=a=>{if(a=document.getElementById(a)){var b=u(a.href,"bg","10");var c=N();if(!(b instanceof g)){var d=L(b,M);d===A&&c(b);b=new g(B(d),f)}b instanceof g||b instanceof g||(b="object"==typeof b&&b.i?b.h():String(b),l.test(b)||(b="about:invalid#zClosurez"),b=new g(b,f));a.href=h(b)}};}).call(this);
