document.writeln("   <ins id=\'scupio-sc-4995-17811-847678\' class=\'scupioadslot\' style=\'display:none;width:100%;height:100px;\'");
document.writeln("    data-sca-pub=\'lRIJBAgyQA==\'");
document.writeln("    data-sca-web=\'4995\'");
document.writeln("    data-sca-category=\'17\'");
document.writeln("    data-sca-cid=\'17811\'");
document.writeln("    data-sca-slot-type=\'PRA\'></ins>");
document.writeln("<script async src=\'https://img.scupio.com/js/ad.js\'></script>");
document.writeln("<script>");
document.writeln("(function(s, c, u, p, i, o, a, d) {");
document.writeln("    \'use strict\';");
document.writeln("    var z=function(t,e,r){var a,n=document.createElement(\'ins\'),s=n.style;for(a in n.className=\'scupioadslot\',r&&(n.id=r),t)t.hasOwnProperty(a)&&(s[a]=t[a]);for(a in e)e.hasOwnProperty(a)&&n.setAttribute(\'data-sca-\'+a,e[a]);return n};");
document.writeln("    (d = s.Scupioads = s.Scupioads || []).push({");
document.writeln("        id: u,");
document.writeln("        callback: function() {");
document.writeln("            p = c.getElementById(u);");
document.writeln("            i = p.style;");
document.writeln("            o = \'inline-block\';");
document.writeln("            p.appendChild(z({");
document.writeln("                display: o,");
document.writeln("                width: \'100%\',");
document.writeln("                height: \'100px\',");
document.writeln("                margin: \'auto\'");
document.writeln("            }, {");
document.writeln("                \'pub\': \'lRIJBAgyQA==\',");
document.writeln("                \'web\': \'4995\',");
document.writeln("                \'category\': \'17\',");
document.writeln("                \'cid\': \'17812\',");
document.writeln("                \'slot-type\': \'STA\'");
document.writeln("            }));");
document.writeln("            i.width = \'100%\';");
document.writeln("            i.height = \'100px\';");
document.writeln("            i.display = o;");
document.writeln("        }");
document.writeln("    });");
document.writeln("    setTimeout(function(){if(!s.Scupioads.init)for(i=d.length-1;0<=i;i--)if(d[i].id===u){d[i].callback(),d[i].callback=function(){};break}},1e3);");
document.writeln("})(window, document, \'scupio-sc-4995-17811-847678\');");
document.writeln("</script>");