document.writeln("<ins id=\'scupio-sc-4995-18725-396182\' class=\'scupioadslot\' style=\'display:block;margin:auto;width:640px;height:0;\'");
document.writeln("    data-sca-pub=\'lRIJBAgyQA==\'");
document.writeln("    data-sca-cid=\'18725\'");
document.writeln("    data-sca-web=\'4995\'");
document.writeln("    data-sca-category=\'17\'");
document.writeln("    data-sca-slot-type=\'preroll\'></ins>");
document.writeln("<script async src=\'https://img.scupio.com/js/ad.js\'></script>");
document.writeln("<script>");
document.writeln("(function(s, c, u, p, i, o, a, d) {");
document.writeln("    \'use strict\';");
document.writeln("    var z=function(t,e,r){var a,n=document.createElement(\'ins\'),s=n.style;for(a in n.className=\'scupioadslot\',r&&(n.id=r),t)t.hasOwnProperty(a)&&(s[a]=t[a]);for(a in e)e.hasOwnProperty(a)&&n.setAttribute(\'data-sca-\'+a,e[a]);return n};");
document.writeln("    (d = s.Scupioads = s.Scupioads || []).push({");
document.writeln("        id: u,");
document.writeln("        callback: function() {");
document.writeln("            p = c.getElementById(u);");
document.writeln("            i = p.style;");
document.writeln("            i.height = \'\';");
document.writeln("            p.appendChild(z({");
document.writeln("                display: \'block\',");
document.writeln("                width: \'300px\',");
document.writeln("                height: \'250px\',");
document.writeln("                margin: \'auto\'");
document.writeln("            }, {");
document.writeln("                \'pub\': \'lRIJBAgyQA==\',");
document.writeln("                \'web\': \'4995\',");
document.writeln("                \'category\': \'17\',");
document.writeln("                \'cid\': \'17523\',");
document.writeln("                \'slot-type\': \'STA\'");
document.writeln("            }));");
document.writeln("        },");
document.writeln("    });");
document.writeln("    setTimeout(function(){var e;if(!s.Scupioads.init)for(e=d.length-1;0<=e;e--)if(d[e].id===u&&!d[e].dispatcherUnreached){d[e].callback(),d[e].callback=function(){},d[e].dispatcherUnreached=!0,c.getElementById(u).id+=\'_dispatcherUnreached\';break}},1e3);");
document.writeln("})(window, document, \'scupio-sc-4995-18725-396182\');");
document.writeln("</script>");
document.writeln("<ins id=\'scupio-sc-4995-18726-55273\' class=\'scupioadslot\' style=\'display:inline-block;width:100%;height:0\'");
document.writeln("data-sca-pub=\'lRIJBAgyQA==\'");
document.writeln("data-sca-cid=\'18726\'");
document.writeln("data-sca-web=\'4995\'");
document.writeln("data-sca-category=\'17\'");
document.writeln("data-sca-slot-type=\'inread\'");
document.writeln("data-sca-fixed=\'1\'></ins>");
document.writeln("<script async src=\'https://img.scupio.com/js/ad.js\'></script>");
document.writeln("<script>");
document.writeln("(function(s, c, u, p, i, o, a, d) {");
document.writeln("    \'use strict\';");
document.writeln("    var z=function(t,e,r){var a,n=document.createElement(\'ins\'),s=n.style;for(a in n.className=\'scupioadslot\',r&&(n.id=r),t)t.hasOwnProperty(a)&&(s[a]=t[a]);for(a in e)e.hasOwnProperty(a)&&n.setAttribute(\'data-sca-\'+a,e[a]);return n};");
document.writeln("    (d = s.Scupioads = s.Scupioads || []).push({");
document.writeln("        id: u,");
document.writeln("        callback: function() {");
document.writeln("            p = c.getElementById(u);");
document.writeln("            i = p.style;");
document.writeln("            i.height = \'\';");
document.writeln("            p.appendChild(z({");
document.writeln("                display: \'block\',");
document.writeln("                width: \'300px\',");
document.writeln("                height: \'250px\',");
document.writeln("                margin: \'auto\'");
document.writeln("            }, {");
document.writeln("                \'pub\': \'lRIJBAgyQA==\',");
document.writeln("                \'web\': \'4995\',");
document.writeln("                \'category\': \'17\',");
document.writeln("                \'cid\': \'17523\',");
document.writeln("                \'slot-type\': \'STA\'");
document.writeln("            }));");
document.writeln("        }");
document.writeln("    });");
document.writeln("    setTimeout(function(){var e;if(!s.Scupioads.init)for(e=d.length-1;0<=e;e--)if(d[e].id===u&&!d[e].dispatcherUnreached){d[e].callback(),d[e].callback=function(){},d[e].dispatcherUnreached=!0,c.getElementById(u).id+=\'_dispatcherUnreached\';break}},1e3);");
document.writeln("})(window, document, \'scupio-sc-4995-18726-55273\');");
document.writeln("</script>");